### ISSUE TITLE
Client for scala 2.11 not published

### ISSUE THREAD

**Issue by lambdista** [takezoe/solr-scala-client#25]
When adding the dependency in sbt using the following syntax:

"jp.sf.amateras.solr.scala" %% "solr-scala-client" % "0.0.11"

for Scala version 2.11.x I get the following error:

unresolved dependency: jp.sf.amateras.solr.scala#solr-scala-client_2.11;0.0.11: not found

Indeed, pointing the browser at http://amateras.sourceforge.jp/mvn/jp/sf/amateras/solr/scala/ there's no 2.11 version.

**Comment by mavarazy** [comment]
+1

**Comment by takezoe** [comment]
0.0.12 for both of Scala 2.10 and 2.11 has been released.
