### ISSUE TITLE
can we keep new version including 0.0.15 compatible with scala 2.11?

### ISSUE THREAD

**Issue by anicolaspp** [takezoe/solr-scala-client#36]

**Comment by takezoe** [comment]
@anicolaspp Do you need a cross compiled version of 0.0.15 for Scala 2.11?

**Comment by anicolaspp** [comment]
It would be nice if we could keep incoming versions compatible with Scala 2.11, at least for some time :)

**Comment by takezoe** [comment]
OK, I will add cross build setting and publish 0.0.15 for Scala 2.11 as soon as possible.

**Comment by anicolaspp** [comment]
This is just perfect. Please, let me know when it will be published

**Comment by takezoe** [comment]
Published. It will take some time to sync to the Maven central repository.
