### ISSUE TITLE
want to stop dependency on Netty 4.0

### ISSUE THREAD

**Issue by masahitojp** [takezoe/solr-scala-client#40]
I use playframework 2.6 + NettyServer. It depends on netty 4.1.

https://www.playframework.com/documentation/2.6.x/Highlights26#Akka-HTTP-Server-Backend

solr-scala-client(Asynchronous API) depends on async-http-client 2.0. It depends on Netty 4.0 (by the way, 2.1-alpha uses netty 4.1)

https://github.com/AsyncHttpClient/async-http-client
https://github.com/AsyncHttpClient/async-http-client/issues/1161

## Suggestion

- Synchronous API and Asynchronous API libraries are separated
- update to async-http-client 2.1-alpha

Everyone What do you think?

**Comment by takezoe** [comment]
How about switching to another HTTP client library (e.g. OkHttp3)?

**Comment by masahitojp** [comment]
> How about switching to another HTTP client library (e.g. OkHttp3)?

It sounds nice 👍 . (Since ahc 2.1 is still alpha, it seems that the interface will change so much... )
