### ISSUE TITLE
Simple Question

### ISSUE THREAD

**Issue by eakarsu** [takezoe/solr-scala-client#62]
I need to use this library form scala but I could not prepare sbt file properly. I have this in sbt.
But it could not find solr client. Any help to resolve this?

scalaVersion := "2.11.12"
libraryDependencies in ThisBuild ++= Seq(
  "org.apache.spark" %% "spark-core" % "2.3.0",
  "org.apache.spark" %% "spark-streaming" % "2.3.0",
  "org.apache.spark" %% "spark-sql" % "2.3.0",
  "com.couchbase.client" %% "spark-connector" % "2.3.0",
  "com.github.takezoe" %% "solr-scala-client" %  "0.0.21"
)

**Comment by takezoe** [comment]
Sorry, 0.0.21 seems to be not published to Maven central somehow. Could you try to use 0.0.20 for now? I will publish 0.0.21 within few days.

**Comment by takezoe** [comment]
See also: https://github.com/takezoe/solr-scala-client/issues/61

**Comment by takezoe** [comment]
Published. It will be available on Maven Central shortly.
